export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css';
import Providers from '../components/Providers';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
